### ISSUE TITLE
Release tags missing

### ISSUE THREAD

**Issue by sometimesfood** [mit-pdos/xv6-public#9]
The release tags from the old xv6 repository (git://pdos.csail.mit.edu/xv6/xv6.git) seem to be missing in this repository.

Could you please use `git push --tags` to push your release tags? Thanks!

**Comment by kaashoek** [comment]
done.

**Comment by sometimesfood** [comment]
Great, thanks!

There are some unusual tags in the repository, did you push these by accident or did you do so on purpose? (The old repository only contained the `xv6-revN` tags.)

The following tags are a little bit confusing given that they are typically also used for a branch and a remote:

- master
- origin

**Comment by kaashoek** [comment]
Thanks for catching that.  I deleted those tags.

The old private repo contained them (i cannot recall why), but not the old
public repo.  I pushed the tags from the old private repo.

**Comment by sometimesfood** [comment]
Great, thank you!
